name: message_builder
version: 0.1.3+4
description: Generate serializable Dart classes from a schema
author: Nate Bosch <nbosch1@gmail.com>
homepage: https://github.com/natebosch/message_builder

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: ">=0.11.0 <0.13.0"
  build_config: ">=0.2.1 <0.4.0"
  code_builder: ^3.1.1
  dart_style: ^1.0.0
  yaml: ^2.1.0

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ">=0.9.0 <0.11.0"
  path: ^1.5.0
  test: ^1.0.0
