name: message_builder
version: 0.2.0-dev
description: Generate serializable Dart classes from a schema
author: Nate Bosch <nbosch1@gmail.com>
homepage: https://github.com/natebosch/message_builder

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  build: '>=0.11.0 <0.13.0'
  code_builder: ^3.0.0
  dart_style: ^1.0.0
  yaml: ^2.1.0
  build_config: ^0.2.1

dev_dependencies:
  build_runner: ^0.7.0
  build_test: '>=0.9.0 <0.11.0'
  path: ^1.5.0
  test: ^0.12.0
